service: todolists-on-herbs-serverless

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
useDotenv: true
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  role: 
  timeout: 100
  memorySize: 1024
  environment:
      NODE_ENV: ${env:NODE_ENV}
      HERBS_EXCEPTION: ${env:HERBS_EXCEPTION}
functions:
  rest:
    name: restAPI
    handler: index.express
    events:
      - http: ANY /
  graphql:
    name: graphql
    handler: index.apollo
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true

  herbsshelf:
    name: herbsShelf
    handler: index.herbsshelf
    events:
      - http:
          path: herbsshelf
          method: get
          cors: true
  crateItem:
    name: create_item
    handler: index.createItem
    events:
      - http:
          path: items
          method: post
          cors: true
  createLists:
    name: create_lists
    handler: index.createList
    events:
      - http:
          path: lists
          method: post
          cors: true
  deleteItem:
    name: delete_item
    handler: index.deleteItem
    events:
      - http:
          path: items/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  deleteLists:
    name: delete_lists
    handler: index.deleteList
    events:
      - http:
          path: lists/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  getItems:
    name: get_items
    handler: index.getItems
    events:
      - http:
          path: items
          method: get
          cors: true
  getLists:
    name: get_lists
    handler: index.getLists
    events:
      - http:
          path: lists
          method: get
          cors: true
  updateItem:
    name: update_item
    handler: index.updateItem
    events:
      - http:
          path: items/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
  updateLists:
    name: update_lists
    handler: index.updateLists
    events:
      - http:
          path: lists/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
custom:
  serverless-offline:
    noPrependStageInUrl: true
